# Generated by Django 4.1.7 on 2023-11-29 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiejemplo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tipo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='vidaslvl',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
